baseURL = "https://www.fd-seminar.xyz"
languageCode = "en-us"
title = "FD Seminar"
theme = "hyde-hyde"
buildFuture = true

[outputs]
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.txt]
    baseName    = "announcement"
    mediaType   = "text/plain"
    isPlainText = true

[params]
  description = "Online seminar on representation theory of finite-dimensional algebras"
  postNavigation = true
  relatedPosts = true
  mainSections = ["talks"]
  bbbURL = "https://bbb.fd-seminar.xyz"
  mailinglistURL = "https://listen.uni-bonn.de/wws/info/fd-seminar"
  toc = "hugo"
  markup = "mmark"

[[menu.main]]
  name = "Home"
  identifier = "home"
  URL = "/"
  weight = 100

[[menu.main]]
  name = "BigBlueButton"
  identifier = "bbb"
  URL = "https://bbb.fd-seminar.xyz"

[[menu.main]]
  name = "Mailing list"
  identifier = "mailinglist"
  url = "https://listen.uni-bonn.de/wws/info/fd-seminar"

[related]

threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100
